import {
  boolean,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";
import { agents } from "./agents.js";
import { companies } from "./companies.js";

export const calendarEvents = pgTable(
  "calendar_events",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    companyId: uuid("company_id").notNull().references(() => companies.id, { onDelete: "cascade" }),
    userId: text("user_id").notNull(),
    kind: text("kind").notNull().default("reminder"),
    title: text("title").notNull(),
    body: text("body"),
    status: text("status").notNull().default("active"),
    scheduleKind: text("schedule_kind").notNull(),
    anchorAt: timestamp("anchor_at", { withTimezone: true }),
    intervalUnit: text("interval_unit"),
    intervalCount: integer("interval_count"),
    timeOfDay: text("time_of_day"),
    cronExpression: text("cron_expression"),
    timezone: text("timezone").notNull().default("UTC"),
    endAt: timestamp("end_at", { withTimezone: true }),
    maxOccurrences: integer("max_occurrences"),
    allDay: boolean("all_day").notNull().default(false),
    durationMinutes: integer("duration_minutes"),
    nextRunAt: timestamp("next_run_at", { withTimezone: true }),
    lastFiredAt: timestamp("last_fired_at", { withTimezone: true }),
    occurrenceCount: integer("occurrence_count").notNull().default(0),
    notify: boolean("notify").notNull().default(true),
    channels: jsonb("channels").$type<string[]>().notNull().default(["desktop"]),
    leadTimeMinutes: integer("lead_time_minutes").notNull().default(0),
    slackTarget: text("slack_target"),
    source: text("source").notNull().default("paperclip"),
    externalId: text("external_id"),
    externalCalendarId: text("external_calendar_id"),
    createdByUserId: text("created_by_user_id"),
    createdByAgentId: uuid("created_by_agent_id").references(() => agents.id, { onDelete: "set null" }),
    updatedByUserId: text("updated_by_user_id"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    companyUserIdx: index("calendar_events_company_user_idx").on(table.companyId, table.userId),
    nextRunIdx: index("calendar_events_next_run_idx").on(table.nextRunAt),
    statusIdx: index("calendar_events_status_idx").on(table.status),
    companyAnchorIdx: index("calendar_events_company_anchor_idx").on(table.companyId, table.anchorAt),
  }),
);

export const calendarEventDeliveries = pgTable(
  "calendar_event_deliveries",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    companyId: uuid("company_id").notNull().references(() => companies.id, { onDelete: "cascade" }),
    eventId: uuid("event_id").notNull().references(() => calendarEvents.id, { onDelete: "cascade" }),
    userId: text("user_id").notNull(),
    channel: text("channel").notNull(),
    status: text("status").notNull().default("pending"),
    title: text("title").notNull(),
    body: text("body"),
    url: text("url"),
    scheduledFor: timestamp("scheduled_for", { withTimezone: true }).notNull(),
    firedAt: timestamp("fired_at", { withTimezone: true }).notNull().defaultNow(),
    deliveredAt: timestamp("delivered_at", { withTimezone: true }),
    failureReason: text("failure_reason"),
    dedupeKey: text("dedupe_key").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    dedupeKeyUq: uniqueIndex("calendar_event_deliveries_dedupe_key_uq").on(table.dedupeKey),
    userChannelStatusIdx: index("calendar_event_deliveries_user_channel_status_idx").on(
      table.userId,
      table.channel,
      table.status,
    ),
    eventCreatedIdx: index("calendar_event_deliveries_event_created_idx").on(table.eventId, table.createdAt),
  }),
);
